# Concurrency In Go

## 第4章 GO语言并发编程范式

### 错误处理

在并发编程中,错误可能很难正确的被处理.有时候我们花了很多时间思考我们在每个层级上应该如何共享和协调信息,却忘记考虑如何优雅地处理错误.GO没有使用常见的错误异常模型,这也同样声明了一件事:GO的设计者认为错误处理同样重要.在开发程序时,我们应该给予错误和算法一样的关注度.本着这个态度,让我们来看看在处理多个并发进程时,我们如何做到这一点.

错误处理最本质的点在于:**谁应该负责处理错误?**在某些情况下,程序需要停止,并且将错误传递到更高层(调用栈的上一层),然后对该错误进行处理.那么谁应该来负责这件事呢?

在并发进程中,这个问题变的更复杂.因为并发进程独立于其父进程或兄弟进程运行,它可能很难判断当出现错误时,自己应该如何处理.

例:

```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	checkStatus := func(done <-chan interface{}, urls ...string) <-chan *http.Response {
		responses := make(chan *http.Response)
		go func() {
			defer close(responses)
			for _, url := range urls {
				resp, err := http.Get(url)
				if err != nil {
					fmt.Println(err)
					continue
				}

				select {
				case <-done:
					return
				case responses <- resp:
				}
			}
		}()

		return responses
	}

	done := make(chan interface{})
	defer close(done)
	urls := []string{"https://www.baidu.com", "https://badHost"}
	for response := range checkStatus(done, urls...) {
		fmt.Printf("Response: %v\n", response.Status)
	}
}
```

运行结果:

```
go run occurErrorInGoroutine.go 
Response: 200 OK
Get "https://badHost": dial tcp: lookup badHost: no such host
```

- 第16行:`fmt.Println(err)`.这一行中,goroutine已经在尽最大努力的展示错误信号了.但也仅仅是将错误信号展示出来.问题的关键点在于:**它无法将错误信号返回!**对于这个goroutine而言,多少个错误才算多?当遇到错误时,它是否该继续向这个url发起请求?

这段代码中,并没有给goroutine任何处理错误的可能性.而goroutine也不能不处理这个错误(意思就是直接抛弃掉这个错误),因此goroutine唯一能做的就是:打印错误并希望它的调用者能注意到这个错误.别把你的goroutine放到如此尴尬的处境之下.此处建议把关注点分离:**一般来讲,你的并发进程应该把错误发送到程序的另一部分中,这样程序状态的完整信息就被保存下来了,而且留出了余地,让调用者可以做出更明智的决定来处理它**.

上边的例子可以进行如下改写:

```go
package main

import (
	"fmt"
	"net/http"
)

type Result struct {
	Error    error
	Response *http.Response
}

func main() {
	checkStatus := func(done <-chan interface{}, urls ...string) <-chan Result {
		results := make(chan Result)
		go func() {
			defer close(results)
			for _, url := range urls {
				resp, err := http.Get(url)
				result := Result{
					Error:    err,
					Response: resp,
				}
				select {
				case <-done:
					return
				case results <- result:
				}
			}
		}()

		return results
	}

	done := make(chan interface{})
	defer close(done)
	urls := []string{"https://www.baidu.com", "http://badHost"}
	for result := range checkStatus(done, urls...) {
		if result.Error != nil {
			fmt.Printf("error: %v\n", result.Error)
			continue
		}

		fmt.Printf("Response: %v\n", result.Response.Status)
	}
}
```

运行结果:

```
go run sendErrorInGoroutine.go
Response: 200 OK
error: Get "http://badHost": dial tcp: lookup badHost: no such host
```

- 第8行:`type Result struct`.此处创建了一个类型.该类型可以同时包含`*http.Respose`和goroutine循环迭代发送请求时可能出现的错误
- 第14行:`checkStatus := func(done <-chan interface{}, urls ...string) <-chan Result`.此处返回了一个只读channel,以便调用者可以检索循环迭代的结果
- 第20行:`result := Result{...}`.此处创建`Result`类型实例,并设置了`Error`和`Response`字段的值
- 第27行:`case results <- result:`.将结果写入管道
- 第39行:`if result.Error != nil`.由于在`checkStatus`创建的goroutine中我们写入了错误信息,因此此处可以在main goroutine中,能够拿到由`checkStatus`创建的goroutine中写入的错误并自行处理,若没有错误后续则可以获取详细的响应信息

在这个例子中需要注意的是**如何将潜在的结果与可能出现的错误结合起来(本例中我们采用的是定义结构体的方式将二者结合的)**.也就是说我们已经成功地将错误处理的职责从生产者中分离出来了.这样使得生成goroutine的goroutine(本例中即main goroutine)拥有更多关于正在运行的程序的上下文,并且可以做出关于如何处理错误的更明智的决定.

在前边的例子中,我们仅仅是将错误写入到stdio中.但实际上也可以做其他事情.稍微修改之前的例子,以便在发生三个或更多错误时,停止错误检查.例子如下:

```go
package main

import (
	"fmt"
	"net/http"
)

type Result struct {
	Error    error
	Response *http.Response
}

func main() {
	checkStatus := func(done <-chan interface{}, urls ...string) <-chan Result {
		results := make(chan Result)
		go func() {
			defer close(results)
			for _, url := range urls {
				resp, err := http.Get(url)
				result := Result{
					Error:    err,
					Response: resp,
				}
				select {
				case <-done:
					return
				case results <- result:
				}
			}
		}()

		return results
	}

	done := make(chan interface{})
	defer close(done)

	errCounter := 0
	urls := []string{"https://www.baidu.com", "http://badHostFoo", "http://badHostBar", "http://badHostBaz"}
	for result := range checkStatus(done, urls...) {
		if result.Error != nil {
			fmt.Printf("error: %v\n", result.Error)
			errCounter++
			if errCounter >= 3 {
				fmt.Printf("Occur too many errors, breaking!\n")
				break
			}
			continue
		}

		fmt.Printf("Response: %v\n", result.Response.Status)
	}
}
```

运行结果:

```
go run handleErrorInCaller.go 
Response: 200 OK
error: Get "http://badHostFoo": dial tcp: lookup badHostFoo: no such host
error: Get "http://badHostBar": dial tcp: lookup badHostBar: no such host
error: Get "http://badHostBaz": dial tcp: lookup badHostBaz: no such host
Occur too many errors, breaking!
```

可以看到,由于错误是从`checkStatus()`函数中返回的,而非是在goroutine内部处理的,因此错误处理也遵循了熟悉的GO语言模式.这个例子很简单,但是不要忘记,在更大规模的场景中,main goroutine通常是要协调多个goroutine的结果并制定更复杂的规则来继续或取消子goroutine的.当然,这一小节的主要内容是:**在构建goroutine的返回值时,应该将错误视为一等公民.如果你的goroutine可能产生错误,那么这些错误应该与goroutine的结果紧密结合,并且通过相同的通信线路传递,就像常规的同步函数一样**.